@echo off
echo Starting K-Line System with Conda...

echo Activating conda environment...
call conda activate kline-env

echo Starting backend...
start "Backend" cmd /k "cd services\api && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul

echo Starting frontend...
start "Frontend" cmd /k "cd apps\web && pnpm dev"

echo Both services are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit this launcher...
pause > nul

